name: Penghijauan

on:   
  schedule:
  - cron: "0 10 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   
        with:
         persist-credentials: true
         fetch-depth: 0
         ref: ${{ github.head_ref }}

      - name: Update last planted
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_PLANTED
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
